version: 3

tasks:
  proto:
    cmds:
      - substreams protogen ./substreams.yaml --exclude-paths="sf/ethereum,sf/substreams,google"

  build:
    cmds:
      - cargo build --target wasm32-unknown-unknown --release

  run:
    cmds:
      - task: proto
      - task: build
      - substreams run -e polygon.streamingfast.io:443 masterfile-event-stream-stg-v0.1.0.spkg map_output_events --stop-block 39145427 -p map_registry_events=071402d3A809f7E8b1B1b75AFa3A500D782B757f --production-mode

  pack:
    internal: true
    cmds:
      - substreams pack ./substreams.yaml

  pack:stg:
    cmds:
      - task: prepare:stg
      - task: pack

  prepare:
    internal: true
    cmds:
      - npx mustache config/{{.CONFIG_FILE}} substreams.template.yaml > substreams.yaml

  prepare:stg:
    cmds:
      - task: prepare
        vars:
          CONFIG_FILE: stg.json
